version: '3'

services:
    nodejs:
        image: phillrog/omnistack5-api:prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: node-api
        restart: always
        env_file: .env
        environment:
            - NODE_ENV=prod
        ports:
            - "3001:3001"
        networks:
            - app-network           

networks:
    app-network:
        driver: bridge

volumes:
    dbdata: