version: 2

jobs:
  build_deploy_api:
    docker:
      - image: circleci/node:latest
        user: root
    working_directory: ~/api
    steps:
      - checkout
      - run:
            name: Update to latest npm version
            command: "sudo npm install -g npm@latest"
      - run:
            name: Install dependencies
            command: npm install    
      - run: bash ./setup-heroku.sh        
            

      - run: bash ./setup-heroku.sh

      - run:
            name: Build using `docker-compose`
            command: |
              docker-compose -f docker-compose.prod.yml build

      - add_ssh_keys:
                      fingerprints:
                        - $HEROKU_SSH_FINGERPRINT

      - run:
            name: Generate tag
            command: |
              docker tag $HEROKU_USER/$HEROKU_APP_NAME:prod registry.heroku.com/$HEROKU_APP_NAME/web            
              

      - deploy:
              name: Deploy to Heroku if tests pass and branch is master
              command: |
                if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  
                  docker push  registry.heroku.com/$HEROKU_APP_NAME/web

                  heroku container:release web --app $HEROKU_APP_NAME

                fi

      - run:
            name: Creating Dummy Artifacts
            command: |
              ls > /tmp/artifact-1;
              mkdir /tmp/artifacts;
              ls > /tmp/artifacts/artifact-2;

      - store_artifacts:
            path: /tmp/artifact-1
            destination: artifact-file

      - store_artifacts:
            path: /tmp/artifacts
workflows:
  build_and_test:
    jobs:
      - build_deploy_api

