version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:11-alpine
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Update to latest npm version
          command: "sudo npm install -g npm@latest"
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Build using `docker-compose`
          command: |
            docker-compose build -f .\docker-compose.prod.yml 
  
workflows:
    build:
      jobs:
        - build
