version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.2.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy_heroku:
    steps:
      - checkout
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_FINGERPRINT
      - deploy:
          name: Deploy to Heroku branch master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
              <any other necessary commands for heroku deployment you might need can go here>
            fi
workflows:
    build:
      jobs:
        - build
        - deploy_heroku