version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.2.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Update to latest npm version
          command: "sudo npm install -g npm@latest"
      - restore_cache: 
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install `docker-compose`
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            - setup_remote_docker:
              docker_layer_caching: false 
      - run:
          name: Build using `docker-compose`
          command: |
            docker-compose build -f .\docker-compose.prod.yml 
  
workflows:
    build:
      jobs:
        - build
