version: 2.1

jobs:
  build_api:
    docker:
      - image: circleci/node:latest
        user: root
    working_directory: ~/api
    steps:
      - checkout
      - run:
          name: Update to latest npm version
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install dependencies
          command: npm install      

  deploy_heroku:
    docker:
      - image: circleci/node:latest
        user: root
    working_directory: ~/api
    steps:
      - checkout
      - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose    

workflows:
  build_and_test:
    jobs:
      - build_api
      - deploy_heroku

